### ISSUE TITLE
cant flash

### ISSUE THREAD

**Issue by Trychlik** [michaljach/m365-info#1]
hi, im using ios 13 public beta8 and botoxed 1.3.8
info is read by app correctly, but when i try to flash, nothing happens, it doesnt start

**Comment by michaljach** [comment]
Hi. Are you selecting ZIP file or BIN ? App currently work only with ZIPs from https://m365.botox.bz/.
Whats you firmware version ?

**Comment by Trychlik** [comment]
solved, when i select zip, it works :), "open bin" confused me (1.3.8)
please change text in future version and disable display dim when flashing (it can scary people, that flash will be interrupted, when display goes off)
thanks
