### ISSUE TITLE
Can’t flash 1.3.8 from 1.4.2

### ISSUE THREAD

**Issue by sebekberg** [michaljach/m365-info#2]
Is this app comparable to the Android app with an identical name?

**Comment by sebekberg** [comment]
Do i need to manually flash the bin for BLE 0.72 before flashing a custom fw?

**Comment by michaljach** [comment]
Have you selected BIN instead of ZIP from the app ? It currently says 'Open BIN' which is wrong and will be changed to 'Open ZIP' in the next release. Moreover - if you have 1.4.x you don't need to flash BLE first - it is the case only with 1.5.x

**Comment by landonepps** [comment]
I also have a scooter on 1.4.2, and it didn't work for me either.
It beeps twice and goes all the way until it says DONE!
But it doesn't actually change the firmware version.

**Comment by arvad-art** [comment]
Hello. 
I dont get how this works. When clicking on manage firmware it opens a blank with OPEN BIN AND FLASH - clicking that does nothing? How to use this to change the firmware?

**Comment by landonepps** [comment]
It says bin, but you actually need to use the zip file generated by https://m365.botox.bz/ for it to do anything.

**Comment by arvad-art** [comment]
Thanks! I think i got it. Download the zip file, and open it via the downgr app? 
I made the mistake to upgrade the firmware to 1.5.4 so now it doesnt work anymore. 

Regards. 

Christian Arvad

**Comment by landonepps** [comment]
I recommend using a third-party app like m365 Tools or darknessBot. If you use the Xiaomi app, it will keep prompting you to update. I believe you can still downgrade from 1.5.4 if you have access to an Android phone. You just have to flash the Bluetooth firmware first.

**Comment by arvad-art** [comment]
Thanks for all the help. I havent been able to find any downgrade from 1.5.4 that didnt require soldering etc. If you know how to do it, please let me know :-) 
- thanks!

**Comment by michaljach** [comment]
BLE (bluetooth low energy) BIN flashing is done and waiting for apple approval. You will then be able to flash from 1.5.x. Also BIN/ZIP selection is fixed. Stay tuned.

**Comment by arvad-art** [comment]
That sounds great, thanks! 

Christian Arvad
