### ISSUE TITLE
M365 Pro and 1.6.6 Firmware

### ISSUE THREAD

**Issue by zigad** [michaljach/m365-info#3]
Hey! 
When I try to downgrade or install a new custom firmware to my M365 Pro with 1.6.6 version I am unable to do that 😕 It goes to 100% and says DONE but then nothing happens, even after I restart the scooter

**Comment by michaljach** [comment]
m365 Pro is in the works. Please be patient.

**Comment by robbiet480** [comment]
@michaljach Any update on M365 Pro?

**Comment by Brahmah** [comment]
Are There Any Updates On The M365 Pro Support?
